build_script:
- dnvm install 1.0.0-beta6
- dnu restore
- dnu publish "ConsoleApplication1" --out DeployPackage --configuration Release --runtime dnx-clr-win-x86.1.0.0-beta6 --wwwroot-out "wwwroot" --quiet

artifacts:
- path: DeployPackage
  name: DeployPackage

test: off
